version: '3.7'

services:

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"


  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/e-commerce-nest-microservice/image-registry/client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVER=nats://nats-server:4222

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/e-commerce-nest-microservice/image-registry/auth-ms
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

      
  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/e-commerce-nest-microservice/image-registry/products-ms
    ports:
      - "${PRODUCTS_MS_PORT}:${PRODUCTS_MS_PORT}"

    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
    
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: southamerica-east1-docker.pkg.dev/e-commerce-nest-microservice/image-registry/orders-ms
    environment:
      - PORT=${ORDERS_MS_PORT}
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}



  payment-ms:
    build:
      context: ./payment-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/e-commerce-nest-microservice/image-registry/payment-ms
    ports:
      - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
    environment:
      - PORT=${PAYMENT_MS_PORT}
      - STRIPE_SECRET=${PAYMENT_MS_STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENT_MS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENT_MS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENT_MS_STRIPE_ENDPOINT_SECRET}
      - NATS_SERVER=nats://nats-server:4222


      