version: '3.7'

services:

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"


  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVER=nats://nats-server:4222

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms-prod
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

      
  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms-prod
    ports:
      - "${PRODUCTS_MS_PORT}:${PRODUCTS_MS_PORT}"

    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
    
  # orders-ms:
  #   depends_on:
  #     - orders-db
  #   build:
  #     context: ./orders-ms
  #     dockerfile: dockerfile.prod
  #   environment:
  #     - PORT=3002
  #     - NATS_SERVER=nats://nats-server:4222
  #     - DATABASE_URL=postgres://postgres:postgres123@orders-db:5432/ordersdb?schema=public



  payment-ms:
    build:
      context: ./payment-ms
      dockerfile: dockerfile.prod
    image: payment-ms-prod
    ports:
      - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
    environment:
      - PORT=${PAYMENT_MS_PORT}
      - STRIPE_SECRET=${PAYMENT_MS_STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENT_MS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENT_MS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENT_MS_STRIPE_ENDPOINT_SECRET}
      - NATS_SERVER=nats://nats-server:4222


      